####################################
# Поведение при старте
####################################
# Пользователь guest отключён через definitions.json
# (сложный пароль + нет прав доступа)
# loopback_users.guest не требуется


############################
# Загрузка definitions
# Все vhost / users / permissions / exchanges / queues
# описываются декларативно
############################
management.load_definitions = /etc/rabbitmq/definitions.json


####################################
# Management Plugin
####################################
management.tcp.port = 15672
management.tcp.ip = 0.0.0.0


####################################
# Logging
####################################
# Вывод логов в консоль (для Docker)
log.console = true
log.console.level = info

# Уровень логирования для отладки
# log.console.level = debug
# log.console.level = warning
# log.console.level = error

# Детализация логов по компонентам
# log.connection.level = info
# log.channel.level = info
# log.queue.level = info

# Формат логов (JSON для парсинга)
# log.formatter = json

############################
# Безопасность диска
# ⚠️ Если задать оба (absolute и relative), то RabbitMQ будет
# учитывать только абсолютный порог (absolute).
############################
#disk_free_limit.relative = 1.0
disk_free_limit.absolute = 2GB

############################
# Контроль памяти
# При достижении 70% доступной памяти
# RabbitMQ включает back-pressure
############################
vm_memory_high_watermark.relative = 0.7


############################
# Network
############################
listeners.tcp.default = 5672
